chore: add `rust-toolchain.toml`
vapoursynth4-sys only builds on stable at the moment because of its use
of `copy_from_nonoverlapping()`. Building on beta or nightly yields:

    error: `std::ptr::mut_ptr::<impl *mut T>::copy_from_nonoverlapping` is not yet stable as a const fn
       --> vapoursynth4-sys\src\helper.rs:179:13
        |
    179 |             dstp.copy_from_nonoverlapping(srcp, row_size * height);
        |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = help: add `#![feature(const_intrinsic_copy)]` to the crate attributes to enable

This patch adds a `rust-toolchain.toml` file to pin the toolchain to
stable.